# File: numiproof-air/Cargo.toml
[package]
name = "numiproof-air"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
serde = { version = "1", features = ["derive"] }
bincode = "1"