# File: numiproof-hash/Cargo.toml
[package]
name = "numiproof-hash"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
sha3 = "0.10"
rand = "0.8"
serde = { version = "1", features = ["derive"] }